// ======================================================================
//  Entity: Report
//  Attributes : reportID, reportType, generatedBy, generatedDate
//  Methods    : generateBorrowReport, generateFineReport,
//               generateInventoryReport, generateUserReport
// ======================================================================

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class Report {

    private String    reportId;
    private String    reportType;
    private String    generatedBy;
    private LocalDate generatedDate;

    private List<BorrowRecord> borrowRecords = new ArrayList<>();
    private List<Fine>         fines         = new ArrayList<>();
    private List<Book>         inventory     = new ArrayList<>();
    private List<User>         users         = new ArrayList<>();

    public Report(String reportId, String generatedBy) {
        this.reportId     = reportId;
        this.generatedBy  = generatedBy;
        this.generatedDate = LocalDate.now();
    }

    public void generateBorrowReport() {
        this.reportType = "Borrow Report";
        System.out.println("\n" + "=".repeat(50));
        System.out.println("  " + reportType + "  |  " + generatedDate);
        System.out.println("  Generated by: " + generatedBy);
        System.out.println("=".repeat(50));
        for (BorrowRecord r : borrowRecords) System.out.println("  " + r);
    }

    public void generateFineReport() {
        this.reportType = "Fine Report";
        double total = fines.stream().mapToDouble(Fine::getAmount).sum();
        System.out.println("\n" + "=".repeat(50));
        System.out.println("  " + reportType + "  |  " + generatedDate);
        System.out.println("  Total Fines: " + total + " BDT");
        System.out.println("=".repeat(50));
        for (Fine f : fines) System.out.println("  " + f);
    }

    public void generateInventoryReport() {
        this.reportType = "Inventory Report";
        System.out.println("\n" + "=".repeat(50));
        System.out.println("  " + reportType + "  |  " + generatedDate);
        System.out.println("=".repeat(50));
        for (Book b : inventory) System.out.println("  " + b);
    }

    public void generateUserReport() {
        this.reportType = "User Report";
        System.out.println("\n" + "=".repeat(50));
        System.out.println("  " + reportType + "  |  " + generatedDate);
        System.out.println("=".repeat(50));
        for (User u : users) System.out.println("  " + u);
    }

    // ── Setters for data injection ──────────────────────────────────
    public void setBorrowRecords(List<BorrowRecord> records) { this.borrowRecords = records; }
    public void setFines(List<Fine> fines)                   { this.fines = fines; }
    public void setInventory(List<Book> inventory)           { this.inventory = inventory; }
    public void setUsers(List<User> users)                   { this.users = users; }
}
